#!/usr/bin/env bash
#print "Best School" 10 times
#on the 9th iteration print hi

count=0

while [ $count -lt 10 ]
do
if [ $count -eq 3 ]
then
    echo "bad luck"
elif [ $count -eq 7 ]
then
    echo "good luck"
   
else
    echo "Best School"
fi
	(( count++ ))
done