#!/usr/bin/env bash
#displays numbers 1 to 20 in addition to;
#bad luck from china on the 4rth iteration
#bad luck from japan on the 9th iteration
#bad luck from italy for the 17th iteration

count=1

while [ $count -le 20 ]
do
    echo "$count"
    case $count in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    (( count++ ))

done